version: "3.9"
services:
  postgres:
    image: postgres
    command: postgres -c 'max_connections=200'
    restart: always
    networks:
      - net
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "${DATABASE_PASSWORD}"
      POSTGRES_USER: "${DATABASE_USERNAME}"
      POSTGRES_DB: "${DATABASE_NAME}"
      DATABASE_HOST: "${DATABASE_HOST}"

volumes:
  api:

networks:
  net:
    driver: bridge
